flowchart TD
    p0((Channel.fromPath))
    p1([splitCsv])
    p2([map])
    p3[NF_HISTOQC:RUN_HISTOQC:HISTOQC]
    p4(( ))
    p5(( ))
    p6([collect])
    p7[NF_HISTOQC:COLLECT_RESULTS:COLLECT]
    p8(( ))
    p0 --> p1
    p1 --> p2
    p2 -->|images| p3
    p3 -->|results| p6
    p3 --> p5
    p3 -->|output| p4
    p6 --> p7
    p7 --> p8
